version: "3.7"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: flask_app
        environment:
            - DB_NAME=db
            - DB_HOST=db
            - DB_PASSWORD=password
            - DB_USER=user
            - DB_PORT=5432
        ports:
            - 5000:5000
        volumes:
            - .:/code/
        depends_on:
            - db

    db:
        image: postgres:13
        container_name: flask_app_db
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=db
        ports:
            - 5433:5432