nameOverride: ""
fullnameOverride: ""

replicaCount: 1

image:
  # TODO - update image params when image is pushed to repo.
  repository: bimie/flask-bubble-sort
  #digest: 
  tag: latest

service:
  type: NodePort
  portName: deppkg-port
  exposedPort: 5000
  targetPort: 5000
  nodePort: 30080

envVars:
  DB_HOST: "localhost"
  DB_NAME: "postgres"

secrets: 
  deppkg-cud-db-creds:
    data:
      DB_USER: "postgres"
      DB_PASS: "postgres"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /msapi/deppkg
    port: deppkg-port

readinessProbe:
  httpGet:
    path: /msapi/deppkg
    port: deppkg-port
