openapi: 3.0.1
info:
  title: ortelius-ms-dep-pkg-r
  version: 1.0.0
  description: 'Description to be entered here'
  termsOfService: http://swagger.io/terms/
  contact:
    email: xyz@deployhub.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://
paths:
  "/msapi/deppkg":
    get:
      tags:
      - ortelius-ms-dep-pkg-r-rest
      operationId: getComponentDepPkg
      parameters:
      - name: compid
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: deptype
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/ComponentDepPkg"
components:
  schemas:
    ComponentDepPkg:
      type: object
      properties:
        packagename:
          type: string
        packageversion:
          type: string
        name:
          type: string
        url:
          type: string
        summary:
          type: string