---
name: Build/Push Image and Release Charts

on:
  push:
    branches:
      - main
    paths-ignore:
      - "chart/ms-dep-pkg-r/Chart.yaml"
      - "chart/ms-dep-pkg-r/values.yaml"

permissions: read-all

env:
  BRANCH: ${{ github.head_ref || github.ref_name }}
  COMPNAME: ${{ github.event.repository.name }}
  DHPASS: ${{ secrets.DHPASS }}
  DHURL: https://console.deployhub.com
  DHUSER: ${{ secrets.DHUSER }}
  QUAY_PASS: ${{ secrets.QUAY_PASSWORD }}
  QUAY_USER: ${{ secrets.QUAY_USERID }}
  REGISTRY: quay.io

jobs:
  setenv:
    runs-on: ubuntu-latest

    outputs:
      short_sha: ${{ steps.env.outputs.short_sha }}
      chart_version: ${{ steps.env.outputs.chart_version }}
      image_version: ${{ steps.env.outputs.image_version }}
      image_tag: ${{ steps.env.outputs.image_tag }}
      image_repo_tag: ${{ steps.env.outputs.image_repo_tag }}
      registry: ${{ steps.env.outputs.registry }}
      quay_user: ${{ steps.env.outputs.quay_user }}
      quay_pass: ${{ steps.env.outputs.quay_pass }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          fetch-depth: 1

      - name: Export env
        id: env
        run: |
          echo "short_sha=$(echo ${{ github.sha }} | cut -c 1-6)" >> "$GITHUB_OUTPUT"
          echo "chart_version=10.0.${{ github.run_number }}" >> "$GITHUB_OUTPUT"
          echo "image_version=10.0.${{ github.run_number }}-g$(echo ${{ github.sha }} | cut -c 1-6)" >> "$GITHUB_OUTPUT"
          echo "image_tag=${{ env.BRANCH }}-v10.0.${{ github.run_number }}-g$(echo ${{ github.sha }} | cut -c 1-6)" >> "$GITHUB_OUTPUT"
          echo "image_repo_tag=${{ env.REGISTRY }}/${{ github.repository }}:${{ env.BRANCH }}-v10.0.${{ github.run_number }}-g$(echo ${{ github.sha }} | cut -c 1-6)" >> "$GITHUB_OUTPUT"
          echo "registry=${{ env.REGISTRY }}" >> "$GITHUB_OUTPUT"
          echo "quay_user=${{ env.QUAY_USER }}" >> "$GITHUB_OUTPUT"
          echo "quay_pass=$${ env.QUAY_PASS }}" >> "$GITHUB_OUTPUT"

  release:
    runs-on: ubuntu-latest
    needs: setenv

    outputs:
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        id: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Login to Quay
        id: login
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ${{ needs.setenv.outputs.registry }}
          username: ${{ needs.setenv.outputs.quay_user }}
          password: ${{ needs.setenv.outputs.quay_pass }}

      - name: Build and Push Docker Image
        id: build
        uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # v3.3.1
        with:
          push: true
          tags: ${{ needs.setenv.outputs.image_repo_tag }}

  trivy:
    runs-on: ubuntu-latest
    needs: [setenv, release]

    permissions:
      security-events: write
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # master
        with:
          image-ref: ${{ needs.setenv.outputs.image_repo_tag }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@168b99b3c22180941ae7dbdd5f5c9678ede476ba # v2.2.7
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  helm:
    runs-on: ubuntu-latest
    needs: [setenv, release]

    permissions:
      security-events: write
      statuses: write
      contents: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        id: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Configure Git
        id: git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Update Values and Chart
        id: chart
        uses: fjogeleit/yaml-update-action@d98ee6a10a971effea75480e3f315e4dacc89a23 # main
        with:
          message: "Update Image Version to ${{ needs.setenv.outputs.image_tag }}"
          commitUserName: $GITHUB_ACTOR
          commitUserEmail: $GITHUB_ACTOR@users.noreply.github.com
          branch: main
          masterBranchName: main
          changes: |
            {
              "chart/${{ github.event.repository.name }}/values.yaml":
              {
                "image.repository": "${{ needs.setenv.outputs.registry }}/${{ github.repository }}",
                "image.tag": "${{ needs.setenv.outputs.image_tag }}",
                "image.sha": "${{ needs.release.outputs.digest }}"
              },
              "chart/${{ github.event.repository.name }}/Chart.yaml":
              {
                "version": "${{ needs.setenv.outputs.chart_version }}",
                "appVersion": "${{ needs.setenv.outputs.chart_version }}"
              }
            }
      - name: Install Helm
        uses: azure/setup-helm@5119fcb9089d432beecbf79bb2c7915207344b78 # v3.5
        with:
          version: v3.10.0

      - name: Prepare GPG key
        run: |
          gpg_dir=.cr-gpg
          mkdir "$gpg_dir"
          keyring="$gpg_dir/secring.gpg"
          base64 -d <<< "$GPG_KEYRING_BASE64" > "$keyring"
          passphrase_file="$gpg_dir/passphrase"
          echo "$GPG_PASSPHRASE" > "$passphrase_file"
          echo "CR_PASSPHRASE_FILE=$passphrase_file" >> "$GITHUB_ENV"
          echo "CR_KEYRING=$keyring" >> "$GITHUB_ENV"
        env:
          GPG_KEYRING_BASE64: "${{ secrets.GPG_KEYRING_BASE64 }}"
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@98bccfd32b0f76149d188912ac8e45ddd3f8695f # v1.4.1
        with:
          charts_dir: chart
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  sbom:
    runs-on: ubuntu-latest
    needs: [setenv, release]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        id: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Generate SBOM
        uses: anchore/sbom-action@07978da4bdb4faa726e52dfc6b1bed63d4b56479 # v0.13.3
        id: sbom
        with:
          format: cyclonedx-json
          output-file: /tmp/cyclonedx.json
          upload-artifact: false
          upload-release-assets: false
          image: ${{ needs.setenv.outputs.image_repo_tag }}

      - name: Update Compnent
        id: updatecomp
        env:
          SHORT_SHA: ${{ needs.setenv.outputs.short_sha }}
          CHART_VERSION: ${{ needs.setenv.outputs.chart_version }}
          IMAGE_VERSION: ${{ needs.setenv.outputs.image_version }}
          IMAGE_TAG: ${{ needs.setenv.outputs.image_tag }}
          IMAGE_REPO_TAG: ${{ needs.setenv.outputs.image_repo_tag }}
          DIGEST: ${{ needs.release.outputs.digest }}
        run: |
          env | sort
          pip install ortelius-cli
          dh envscript --envvars component.toml --envvars_sh env.sh
          source env.sh
          dh updatecomp --rsp component.toml --deppkg cyclonedx@/tmp/cyclonedx.json

  update-main-chart:
    runs-on: ubuntu-latest
    needs: [helm]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Trigger Rebuild of Main Chart
        uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 # v1.2.2
        with:
          workflow: generate-main-chart.yml
          repo: ortelius/ortelius-charts
          token: ${{ secrets.HELM_INDEXER_TOKEN }}
